"""
Pull column descriptions out of dbt's manifest and keep the ERD from drifting.

Nothing fancy — if docs generate hasn't been run yet we still write empty stubs
so the docs site has somewhere to land.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path


def generate_data_dictionary(root: Path) -> None:
    manifest_path = root / "dbt" / "target" / "manifest.json"
    out_dir = root / "docs" / "data-dictionary"
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / "data-dictionary.md"
    csv_path = out_dir / "data-dictionary.csv"

    rows: list[dict] = []
    if manifest_path.exists():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        for node in manifest.get("nodes", {}).values():
            if node.get("resource_type") != "model":
                continue
            layer = node.get("schema") or node.get("fqn", ["?"])[1] if node.get("fqn") else "?"
            for col_name, col in (node.get("columns") or {}).items():
                rows.append(
                    {
                        "layer": layer,
                        "model": node["name"],
                        "column": col_name,
                        "data_type": (col.get("data_type") or ""),
                        "description": (col.get("description") or ""),
                        "data_owner": (node.get("meta") or {}).get("owner", ""),
                    }
                )

    headers = ["layer", "model", "column", "data_type", "description", "data_owner"]
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=headers)
        w.writeheader()
        for r in rows:
            w.writerow(r)

    lines = ["# Data Dictionary", "", f"Generated models/columns: **{len(rows)}**", ""]
    if not rows:
        lines.append("_Run `dbt docs generate` first to populate from manifest._")
    else:
        current = None
        for r in rows:
            key = f"{r['layer']}.{r['model']}"
            if key != current:
                lines.append(f"## `{key}`")
                lines.append("")
                current = key
            lines.append(f"- `{r['column']}` ({r['data_type']}): {r['description'] or '_TODO_'}")
        lines.append("")
    md_path.write_text("\n".join(lines), encoding="utf-8")


def generate_erd(root: Path) -> None:
    """Write a gold-star Mermaid ERD stub (enriched when manifest exists)."""
    erd_dir = root / "docs" / "erd"
    erd_dir.mkdir(parents=True, exist_ok=True)
    gold = erd_dir / "erd-gold-star.md"
    content = """# Gold Star ERD

```mermaid
erDiagram
    DIM_HCP ||--o{ FCT_RX_DEMAND : prescribes
    DIM_PRODUCT ||--o{ FCT_RX_DEMAND : of_product
    DIM_DATE ||--o{ FCT_RX_DEMAND : in_period
    DIM_GEOGRAPHY ||--o{ FCT_RX_DEMAND : in_geography
    DIM_PAYER_PLAN ||--o{ FCT_RX_DEMAND : under_plan
    DIM_TERRITORY ||--o{ FCT_RX_DEMAND : aligned_to
    DIM_OUTLET ||--o{ FCT_SHIPMENT : ships_to
    DIM_PRODUCT ||--o{ FCT_SHIPMENT : of_product
    DIM_HCO ||--o{ DIM_OUTLET : resolves_to
    DIM_HCP ||--o{ FCT_SP_DISPENSE : prescribes
    DIM_SP ||--o{ FCT_SP_DISPENSE : dispensed_by
    FCT_SP_DISPENSE ||--|| FCT_SP_FUNNEL_EVENT : patient_journey
    DIM_HCP }o--o{ DIM_HCO : affiliated
    DIM_TERRITORY ||--o{ DIM_TERRITORY : rolls_up_to
    DIM_REP ||--o{ DIM_TERRITORY : covers
    MDM_HCP_XREF }o--|| DIM_HCP : resolves_to
```

Regenerated by `pcdm erd`. Source of truth also in `erd.dbml`.
"""
    gold.write_text(content, encoding="utf-8")
